<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="./assets/css/style.css">
    <title>E-commerce</title>
</head>
<body>
    <div id="main_card">
        <header>
            <nav>
                <div class="menu">
                    <img src="./assets/images/logo.svg" alt="logo">
                    <ul>
                        <li>Collections</li>
                    </ul>
                </div>
                <div>
                    <img src="./assets/images/icon-cart.svg" alt="shop-cart" class="icon-cart">
                    <img src="./assets/images/user.svg" alt="user-cart" class="user-cart">
                </div>
            </nav>
        </header>
    