<?php
if (session_status() == PHP_SESSION_NONE) {
    session_start();
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="./assets/css/style.css">
    <title>E-commerce</title>
</head>
<body>
    <div id="main_card">
        <header>
            <nav>
                <div class="menu">
                    <img src="./assets/images/logo.svg" alt="logo">
                    <ul>
                        <li><a href="index.php">Collections</a></li>
                        <li><a href="ajoutProduit.php">Ajouter un produit</a></li>
                    </ul>
                </div>
                <div>
                    <?php 
                        if(isset($_SESSION['user'])) {
                            echo 'Connecté';
                            echo ' <a href="logout.php">Se déconnecter</a>'; // bouton déco
                        } else {
                            echo 'pas connecté';
                            echo ' <a href="hote.php">Se connecter</a>';
                            echo ' <a href="ajoutUser.php">S\'inscrire</a>';
                        }
                    ?>

                    <!-- 
                    <img src="./assets/images/icon-cart.svg" alt="shop-cart" class="icon-cart">
                    <img src="./assets/images/user.svg" alt="user-cart" class="user-cart">
                    -->
                </div>
            </nav>
        </header>
    