<?php
if (session_status() == PHP_SESSION_NONE) {
    session_start();
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="./assets/css/style.css">
    <title>E-commerce</title>
</head>
<body>
    <div id="main_card">
        <header>
            <nav>
                <div class="menu">
                    <img src="./assets/images/logo.svg" alt="logo">
                    <ul>
                        <li><a href="index.php">Collections</a></li>
                        <?php if (isset($_SESSION['user'])): ?>
                        <li><a href="ajoutProduit.php">Ajouter un produit</a></li>
                        <?php endif; ?>
                    </ul>
                </div>
                <div>
                    <img src="./assets/images/icon-cart.svg" alt="shop-cart" class="icon-cart">
                    <div class="user-menu-container">
                    <img 
                        src="<?= isset($_SESSION['user']) ? './assets/images/user-green.svg' : './assets/images/user.svg' ?>" 
                        alt="user-cart" 
                        class="user-cart" 
                        id="userIcon"
                    >

                    <!-- Menu déroulant -->
                    <div class="user-dropdown" id="userDropdown">
                        <?php if (isset($_SESSION['user'])): ?>
                            <a href="logout.php">Déconnexion</a>
                        <?php else: ?>
                            <a href="hote.php">Connexion</a>
                            <a href="ajoutUser.php">Inscription</a>
                        <?php endif; ?>
                    </div>
                </div>
                </div>
            </nav>
        </header>
    