<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="./assets/css/style.css">
    <title>Formulaire</title>
</head>
<body>
    <?php 
    $page = basename($_SERVER['PHP_SELF']);

    if(isset($erreur) && $erreur) : ?>
    <p class="error"><?= htmlspecialchars($erreur) ?></p>
    <?php endif; ?>

    <?php if(isset($success) && $success) : ?>
        <p class="success"><?= htmlspecialchars($success) ?></p>
    <?php endif; ?>

    <?php if($page === 'ajoutUser.php') : ?>
        <h1>Inscription</h1>
        <div class="form">
            <div class="form-content">
                <form action="./ajoutUser.php" method='post'>
                    <input type="hidden" name="csrf_token" value="<?= $_SESSION['csrf_token'] ?>">
                    <label for="email">E-mail :</label>
                    <input type="email" name="email" id="email" required>
                    <label for="password">Mot de passe :</label>
                    <input type="password" name="password" id="password" required>
                    <input type="submit" value="Valider" class="valider">
                </form>
            </div>
        </div>
    <?php elseif ($page === 'hote.php') : ?>
        <h1>Connexion</h1>
        <div class="form">
            <div class="form-content">
                <form action="./hote.php" method='post'>
                    <input type="hidden" name="csrf_token" value="<?= $_SESSION['csrf_token'] ?>">
                    <label for="email">E-mail :</label>
                    <input type="email" name="email" id="email" required>
                    <label for="password">Mot de passe :</label>
                    <input type="password" name="password" id="password" required>
                    <input type="submit" value="Valider" class="valider">
                </form>
            </div>
        </div>
    <?php endif; ?>
</body>