<div class="product">
    <img src="<?= htmlentities($p['image']) ?>" alt="shoes">
    <h1><?= htmlentities($p['titre']) ?></h1>
    <p><?= htmlentities($p['description']) ?></p>
    <p><?= htmlentities($p['prix']) ?> €</p>
    <button>Acheter</button>

    <form action="editProduit.php" method="get">
        <input type="hidden" name="id" value="<?= htmlentities($p['id']) ?>">
        <input type="submit" value="Éditer">
    </form>

    <form action="deleteProduit.php" method="post">
        <input type="hidden" name="id" value="<?= htmlentities($p['id']) ?>">
        <input type="submit" value="Supprimer" onclick="return confirm('Supprimer ce produit ?');">
    </form>
</div>