<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="./assets/css/style.css">
    <title>Formulaire</title>
</head>
<body>
    <h1>S'inscrire</h1>

    <form action="./ajoutUser.php" method='post'>
        <label for="email">E-mail :</label>
        <input type="email" name="email" id="e-mail" required>
        <br>
        <label for="password">Mot de passe :</label>
        <input type="password" name="password" id="password" required>
        <br>
        <input type="submit" value="Ajouter l'utilisateur">
    </form>
</body>